// cSpell:disable

export const medicalNames = [
  'Febre',
  'Astenia',
  'Cefaléia',
  'Sudorese',
  'Calafrios',
  'Cãibras',
  'Prurido',
  'Lacrimejamento',
  'Xantopsia; Iantopsia; Doropsia',
  'Diplopia',
  'Fotofobia',
  'Nistagmo',
  'Escotomas',
  'Alucinações visuais',
  'Ambliopia',
  'Hemianopsia',
  'Amaurose',
  'Otalgia',
  'Otorréia',
  'Otorragia',
  'Hipocusia',
  'Surdez',
  'Acusia',
  'Zumbidos',
  'Vertigem e Tontura',
  'Rinorréia',
  'Epistaxe',
  'Dispneia',
  'Hiposmia',
  'Anosmia',
  'Hiperosmia',
  'Cacosmia',
  'Parosmia',
  'Rinolalia',
  'Polifagia ou hiperorexia',
  'Inapetência ou anorexia',
  'Sialose',
  'Halitose',
  'Disfagia',
  'Pigarro',
  'Disfonia',
  'Afonia',
  'Hemoptise',
  'Vômica',
  'Chieira',
  'Cornagem',
  'Estridor',
  'Tiragem',
  'Soluço',
  'Palpitações',
  'Desmaio e Síncope',
  'Cianose',
  'Edema',
  'Odinofagia',
  'Pirose',
  'Regurgitação',
  'Eructação',
  'Hematêmese',
  'Sialose (sialorréia ou ptialismo)',
  'Náuseas',
  'Vômitos',
  'Dispepsia',
  'Diarreia',
  'Disenteria',
  'Esteatorreia',
  'Melena',
  'Enterorragia',
  'Distensão abdominal',
  'Icterícia',
  'Oligúria',
  'Anúria',
  'Poliúria',
  'Disúria',
  'Noctúria',
  'Polaciúria',
  'Hematúria',
  'Hemoglobinúria',
  'Varicocele',
  'Priapismo',
  'Hemospermia',
  'Ejaculação precoce',
  'Anorgasmia',
  'Polimenorreia',
  'Oligomenorreia',
  'Amenorreia',
  'Hipermenorreia',
  'Hipomenorreia',
  'Menorragia',
  'Metrorragia',
  'Dismenorreia',
  'Cólicas',
  'Dispareunia',
  'Frigidez',
  'Petéquias',
  'Equimoses',
  'Hematomas',
  'Eritemas',
  'Pápulas',
  'Esplenomegalia',
  'Hepatomegalia',
  'Palidez',
  'Galactorreia',
  'Taquicardia',
  'Bradicardia',
  'Exoftalmia',
  'Apatia',
  'Ginecomastia',
  'Macroglossia',
  'Cãibras',
  'Convulsões',
  'Polidipsia',
  'Hirsutismo',
  'Virilismo',
  'Rubor',
  'Amnesia',
  'Disbasia',
  'Paresias',
  'Paralisias',
  'Parestesias',
  'Anestesias',
  'Hipostesia',
  'Hiperestesia',
];
